const Types = {
    GET_PLACES: 'GET_PLACES',
    FAILED_GET_PLACES: 'FAILED_GET_PLACES',
    COMPLETE_GET_PLACES: 'COMPLETE_GET_PLACES',
    ADD_PLACE: 'ADD_PLACE',
    FAILED_ADD_PLACE: 'FAILED_ADD_PLACE',
    COMPLETE_ADD_PLACE: 'COMPLETE_ADD_PLACE',
}

export default Types;